/**
 * The `metric:<id>` concepts, one per catalogue metric. Generated by
 * `npm run contracts:sync` from metrics.yaml (title, purpose, formula,
 * interpretation, pitfalls, references); this file only hands them to the
 * concept registry, which loads every `concepts/*.ts` file.
 */
export { concepts } from "../../generated/catalogue";
