// contracts:sync / contracts:check — the GUI's types, generated from the Python side.
//
//   node packages/contracts/gen.mjs            writes generated/**
//   node packages/contracts/gen.mjs --check    regenerates into a temp directory, diffs, exits 1 on drift
//   options: --repo <dir> (repository root, default ../../..), --out <dir> (default ./generated)
//
// Inputs (never edited here):
//   packages/sdfb-evaluation/src/sdfb_evaluation/schemas/*.schema.json (+ views.sql, __init__.py)
//   config/bq_schema/<dataset>/*.schema.json
//   packages/sdfb-evaluation/src/sdfb_evaluation/catalogue/metrics.yaml
//   generated/knobs.json            (scripts/gui/export_knobs.py)
//   generated/relationships.json    (scripts/gui/export_knobs.py: committed sample relationship models)
//   generated/dlq_rules.json        (scripts/gui/export_knobs.py: DLQ rule → error_type/step/severity)
//   generated/golden/*.json         (scripts/gui/export_golden_fixtures.py)
// Outputs:
//   generated/schemas.ts    zod per BigQuery table + field metadata + vocabularies parsed from descriptions
//   generated/catalogue.ts  the typed metric catalogue + one "metric:<id>" concept per metric
//   generated/knobs.ts      knobs.json, typed (KnobId / ChannelId unions)
//   generated/relationships.ts  relationships.json, typed (RelationshipModelId union)
//   generated/dlqRules.ts   dlq_rules.json, typed (DlqRuleId union) + dlqRuleById
//   generated/manifest.json sha256 of every input, so a hand edit of knobs.json or a golden file is drift too
import { createHash } from "node:crypto";
import { mkdtempSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import YAML from "yaml";

const HERE = dirname(fileURLToPath(import.meta.url));
const HEADER = "// GENERATED by packages/contracts/gen.mjs (npm run contracts:sync). Do not edit.\n";

const EVAL_SCHEMAS = "packages/sdfb-evaluation/src/sdfb_evaluation/schemas";
const BQ_SCHEMAS = "config/bq_schema";
const CATALOGUE = "packages/sdfb-evaluation/src/sdfb_evaluation/catalogue/metrics.yaml";

/**
 * Fields whose description opens with a closed vocabulary. The vocabulary is parsed
 * from the description (never typed here); a description that stops parsing fails
 * the generator. "pipe": `a | b | c — prose`; "quoted": `'a' or 'b'`.
 */
const VOCABULARIES = {
  evaluation_data_history: {
    event: "pipe",
    status: "pipe",
    trigger: "pipe",
    mode: "pipe",
    params_source: "pipe",
    "tables.role": "pipe",
    "tables.scope_mode": "pipe",
    "tables.scope_status": "pipe",
    source_stats_tier: "pipe",
    env: "pipe",
  },
  evaluation_metrics: {
    level: "pipe",
    family: "pipe",
    value_kind: "pipe",
    status: "pipe",
    column_kind: "pipe",
    noise_floor_method: "pipe",
    method: "pipe",
  },
  evaluation_profiles: { profile_kind: "pipe", side: "pipe" },
  evaluation_row_flags: { check: "pipe", source_set: "pipe" },
  validation_runs: { status: "pipe" },
  rag_chunks: { chunk_kind: "quoted" },
};

const PIPE = /^\s*([A-Za-z0-9_+]+(?:\s*\|\s*[A-Za-z0-9_+]+)+)/;
const QUOTED = /^\s*'([a-z0-9_]+)'((?:\s*(?:,|or)\s*'[a-z0-9_]+')+)/;

function sha256(text) {
  return createHash("sha256").update(text).digest("hex");
}

function camel(name) {
  return name.replace(/_([a-z0-9])/g, (_, c) => c.toUpperCase());
}

function pascal(name) {
  const c = camel(name);
  return c[0].toUpperCase() + c.slice(1);
}

function parseVocabulary(description, mode, where) {
  if (mode === "pipe") {
    const match = PIPE.exec(description ?? "");
    if (!match) throw new Error(`${where}: description no longer opens with "a | b | …": ${description}`);
    return match[1].split("|").map((s) => s.trim());
  }
  const match = QUOTED.exec(description ?? "");
  if (!match) throw new Error(`${where}: description no longer opens with "'a' or 'b'": ${description}`);
  return [match[1], ...[...match[2].matchAll(/'([a-z0-9_]+)'/g)].map((m) => m[1])];
}

function tsString(value) {
  return JSON.stringify(value);
}

/** Every input table: name, dataset, repo-relative source path, fields. */
function loadTables(repo) {
  const tables = [];
  const evalDir = join(repo, EVAL_SCHEMAS);
  const init = readFileSync(join(evalDir, "__init__.py"), "utf8");
  const datasetMatch = /dataset: str = "([a-z_]+)"/.exec(init);
  if (!datasetMatch) throw new Error(`${EVAL_SCHEMAS}/__init__.py: default dataset not found`);
  for (const file of readdirSync(evalDir)
    .filter((f) => f.endsWith(".schema.json"))
    .sort()) {
    tables.push({
      name: file.replace(".schema.json", ""),
      dataset: datasetMatch[1],
      source: `${EVAL_SCHEMAS}/${file}`,
      fields: JSON.parse(readFileSync(join(evalDir, file), "utf8")),
    });
  }
  const bqDir = join(repo, BQ_SCHEMAS);
  for (const dataset of readdirSync(bqDir).sort()) {
    const dir = join(bqDir, dataset);
    for (const file of readdirSync(dir)
      .filter((f) => f.endsWith(".schema.json"))
      .sort()) {
      tables.push({
        name: file.replace(".schema.json", ""),
        dataset,
        source: `${BQ_SCHEMAS}/${dataset}/${file}`,
        fields: JSON.parse(readFileSync(join(dir, file), "utf8")),
      });
    }
  }
  const names = tables.map((t) => t.name);
  const duplicate = names.find((n, i) => names.indexOf(n) !== i);
  if (duplicate) throw new Error(`two schema files define table "${duplicate}"`);
  return tables;
}

function loadViews(repo) {
  const sql = readFileSync(join(repo, EVAL_SCHEMAS, "views.sql"), "utf8");
  return [...sql.matchAll(/CREATE OR REPLACE VIEW `\{project\}\.\{dataset\}\.(\w+)`/g)].map((m) => m[1]);
}

const SCALARS = {
  STRING: "z.string()",
  INT64: "z.int()",
  INTEGER: "z.int()",
  FLOAT64: "z.number()",
  FLOAT: "z.number()",
  NUMERIC: "z.number()",
  BIGNUMERIC: "z.number()",
  BOOL: "z.boolean()",
  BOOLEAN: "z.boolean()",
  TIMESTAMP: "z.iso.datetime({ offset: true })",
  DATETIME: "z.iso.datetime({ local: true })",
  DATE: "z.iso.date()",
  JSON: "z.json()",
};

function zodField(table, field, path, vocabularies, indent) {
  const where = `${table}.${path}`;
  let base;
  if (field.type === "RECORD" || field.type === "STRUCT") {
    base = zodObject(table, field.fields ?? [], `${path}.`, vocabularies, indent + "  ");
  } else if (vocabularies[path]) {
    const values = parseVocabulary(field.description, vocabularies[path], where);
    base = `z.enum(${tsString(values)})`;
  } else {
    base = SCALARS[field.type];
    if (!base) throw new Error(`${where}: unsupported BigQuery type ${field.type}`);
  }
  if (field.mode === "REPEATED") return `z.array(${base})`;
  if (field.mode === "REQUIRED") return base;
  return `${base}.nullable()`;
}

function zodObject(table, fields, prefix, vocabularies, indent) {
  const lines = ["z.object({"];
  for (const field of fields) {
    const doc = (field.description ?? "").replace(/\*\//g, "* /").trim();
    if (doc) lines.push(`${indent}  /** ${doc} */`);
    lines.push(
      `${indent}  ${field.name}: ${zodField(table, field, `${prefix}${field.name}`, vocabularies, indent + "  ")},`,
    );
  }
  lines.push(`${indent}})`);
  return lines.join("\n");
}

function stripDescriptions(fields) {
  return fields.map((f) => {
    const out = { name: f.name, type: f.type, mode: f.mode ?? "NULLABLE" };
    if (f.fields) out.fields = stripDescriptions(f.fields);
    return out;
  });
}

function renderSchemas(tables, views, catalogue) {
  const out = [HEADER];
  out.push(`/**
 * zod contracts for every BigQuery table the GUI reads, one per \`*.schema.json\`.
 * Wire format (what the BFF returns and the mock produces): TIMESTAMP → ISO-8601
 * string with offset, INT64 → safe integer, JSON → parsed JSON value, NULLABLE →
 * null (keys always present), REPEATED → array. Vocabularies (\`z.enum\`) are parsed
 * from the column descriptions listed in gen.mjs \`VOCABULARIES\`.
 */
import { z } from "zod";
`);
  const vocabExports = [];
  for (const table of tables) {
    const vocab = VOCABULARIES[table.name] ?? {};
    const ident = camel(table.name);
    out.push(`/** \`${table.dataset}.${table.name}\` — ${table.source} */`);
    out.push(`export const ${ident}RowSchema = ${zodObject(table.name, table.fields, "", vocab, "")};`);
    out.push(`export type ${pascal(table.name)}Row = z.infer<typeof ${ident}RowSchema>;\n`);
    for (const [path, mode] of Object.entries(vocab)) {
      const field = path.split(".").reduce((fields, part, i, parts) => {
        const found = fields.find((f) => f.name === part);
        if (!found) throw new Error(`${table.name}.${path}: no such field`);
        return i === parts.length - 1 ? found : (found.fields ?? []);
      }, table.fields);
      const values = parseVocabulary(field.description, mode, `${table.name}.${path}`);
      vocabExports.push(`  ${tsString(`${table.name}.${path}`)}: ${tsString(values)},`);
    }
  }
  // Consistency between the registry schema and the catalogue.
  const metricTable = tables.find((t) => t.name === "evaluation_metrics");
  if (metricTable) {
    for (const [path, expected] of [
      ["level", catalogue.levels],
      ["family", catalogue.families],
    ]) {
      const field = metricTable.fields.find((f) => f.name === path);
      const values = parseVocabulary(field.description, "pipe", `evaluation_metrics.${path}`);
      if (JSON.stringify(values) !== JSON.stringify(expected))
        throw new Error(
          `evaluation_metrics.${path} (${values.join(", ")}) differs from the catalogue (${expected.join(", ")})`,
        );
    }
  }
  out.push(`/** Closed vocabularies, "<table>.<field path>" → values (parsed from the descriptions). */
export const vocabularies = {
${vocabExports.join("\n")}
} as const;
`);
  out.push(`/** Table metadata: dataset, source file and the field tree (types and modes) the BFF normalizes rows with. */
export const bqTables = ${JSON.stringify(
    Object.fromEntries(
      tables.map((t) => [t.name, { dataset: t.dataset, source: t.source, fields: stripDescriptions(t.fields) }]),
    ),
    null,
    2,
  )} as const;

export type BqTableName = keyof typeof bqTables;
export type BqField = { name: string; type: string; mode: string; fields?: readonly BqField[] };

/** Views defined in ${EVAL_SCHEMAS}/views.sql (the GUI reads \`evaluation_latest\`). */
export const bqViews = ${tsString(views)} as const;
`);
  out.push(`/** Every table's row schema, by table name. */
export const rowSchemas = {
${tables.map((t) => `  ${t.name}: ${camel(t.name)}RowSchema,`).join("\n")}
} as const;
`);
  return out.join("\n");
}

function linkKind(url) {
  if (/\/docs\/adr\//.test(url)) return "adr";
  if (/github\.com\/albertols\/synthetic-llm-dataflow-bigquery/.test(url)) return "code";
  if (/doi\.org|arxiv\.org|jstor|proceedings|papers|acm\.org|springer|wiley|ieee/.test(url)) return "paper";
  return "docs";
}

function renderCatalogue(doc) {
  const metrics = doc.metrics.map((m) => ({
    id: m.id,
    version: String(m.version),
    title: m.title,
    level: m.level,
    family: m.family,
    kinds: m.kinds,
    value_kind: m.value_kind,
    estimator: m.estimator,
    direction: m.direction,
    target: m.target ?? null,
    range: m.range.map((v) => v ?? null),
    thresholds: { warn: m.thresholds.warn ?? null, fail: m.thresholds.fail ?? null, source: m.thresholds.source },
    score: m.score,
    noise_floor: m.noise_floor,
    n_dependent: m.n_dependent,
    baseline: m.baseline,
    uses_ci_bound: m.uses_ci_bound,
    formula: m.formula,
    purpose: m.purpose.trim(),
    interpretation: { good: m.interpretation.good, bad: m.interpretation.bad },
    pitfalls: m.pitfalls,
    references: m.references.map((r) => ({ label: r.label, url: r.url, kind: linkKind(r.url) })),
  }));
  return `${HEADER}/**
 * The metric catalogue (${CATALOGUE}), typed, plus one (i) concept per metric
 * (\`metric:<id>\`; re-exported by src/concepts/catalogue.ts for the concept registry).
 * Reference kinds (paper / docs / adr / code) are classified by URL in gen.mjs.
 */
import { defineConcepts, type Concept } from "../src/concept";

export const catalogueVersion = ${tsString(String(doc.catalogue_version))};
export const catalogueLevels = ${tsString(doc.levels)} as const;
export const catalogueFamilies = ${tsString(doc.families)} as const;
export type CatalogueLevel = (typeof catalogueLevels)[number];
export type CatalogueFamily = (typeof catalogueFamilies)[number];
export type MetricId =
${metrics.map((m) => `  | ${tsString(m.id)}`).join("\n")};

export type ScoreFn = "complement" | "linear" | "ratio_to_one" | "auc" | "none";
export type Direction = "lower_better" | "higher_better" | "target";

export interface CatalogueMetric {
  id: MetricId;
  version: string;
  title: string;
  level: CatalogueLevel;
  family: CatalogueFamily;
  kinds: readonly string[];
  value_kind: string;
  estimator: string;
  direction: Direction;
  /** The value a perfect generator scores; null = data-dependent / 0 / top of range (see the YAML header). */
  target: number | null;
  range: readonly [number | null, number | null];
  thresholds: { warn: number | null; fail: number | null; source: string };
  score: ScoreFn;
  /** Noise method name, or "none". */
  noise_floor: string;
  n_dependent: boolean;
  baseline: boolean;
  uses_ci_bound: boolean;
  formula: string;
  purpose: string;
  interpretation: { good: string; bad: string };
  pitfalls: string;
  references: readonly { label: string; url: string; kind: "paper" | "docs" | "adr" | "code" }[];
}

export const catalogue: readonly CatalogueMetric[] = ${JSON.stringify(metrics, null, 2)};

export const catalogueById: Readonly<Record<MetricId, CatalogueMetric>> = Object.fromEntries(
  catalogue.map((metric) => [metric.id, metric]),
) as Record<MetricId, CatalogueMetric>;

/** One (i) concept per metric: "metric:<id>". */
export const concepts = defineConcepts(
  catalogue.map(
    (m): Concept => ({
      id: \`metric:\${m.id}\`,
      title: m.title,
      purpose: m.purpose,
      formula: m.formula,
      interpretation: { good: m.interpretation.good, bad: m.interpretation.bad },
      pitfalls: m.pitfalls,
      links: m.references.map((r) => ({ label: r.label, url: r.url, kind: r.kind })),
      level: m.level,
    }),
  ),
);
`;
}

function renderKnobs(knobs) {
  for (const key of ["channels", "knobs", "annotations", "measured_sources", "measured"])
    if (!Array.isArray(knobs[key])) throw new Error(`knobs.json: "${key}" must be an array`);
  for (const knob of knobs.knobs)
    for (const key of ["id", "channel", "group", "label", "settable_via", "source"])
      if (!(key in knob)) throw new Error(`knobs.json: knob ${knob.id ?? "?"} lacks "${key}"`);
  return `${HEADER}/** scripts/gui/export_knobs.py → generated/knobs.json, typed. Values come from code with \`path:line\`. */
import type { KnobsFile } from "../src/knobs";

export type ChannelId =
${knobs.channels.map((c) => `  | ${tsString(c.id)}`).join("\n")};
export type KnobId =
${knobs.knobs.map((k) => `  | ${tsString(k.id)}`).join("\n")};

export const knobs: KnobsFile = ${JSON.stringify(knobs, null, 2)};
`;
}

function requireExport(doc, name, arrays) {
  if (doc.generated_by !== "scripts/gui/export_knobs.py")
    throw new Error(`${name}: not written by scripts/gui/export_knobs.py`);
  for (const key of arrays) if (!Array.isArray(doc[key])) throw new Error(`${name}: "${key}" must be an array`);
  const from = doc.exported_from;
  if (!from || !("commit" in from) || !Array.isArray(from.dirty)) throw new Error(`${name}: lacks "exported_from"`);
}

function renderRelationships(doc) {
  requireExport(doc, "relationships.json", ["models"]);
  for (const model of doc.models)
    for (const table of model.tables)
      for (const edge of table.fk)
        for (const key of ["cols", "ref", "ref_cols", "enforced", "role", "drawn_cols"])
          if (!(key in edge)) throw new Error(`relationships.json: ${model.model}.${table.name} edge lacks "${key}"`);
  return `${HEADER}/** scripts/gui/export_knobs.py → generated/relationships.json, typed: the committed sample models. */
import type { RelationshipsFile } from "../src/relational";

export type RelationshipModelId =
${doc.models.map((m) => `  | ${tsString(m.model)}`).join("\n")};

export const relationships: RelationshipsFile = ${JSON.stringify(doc, null, 2)};
`;
}

function renderDlqRules(doc) {
  requireExport(doc, "dlq_rules.json", ["rules"]);
  for (const rule of doc.rules)
    for (const key of ["rule_id", "emitted", "error_type", "pipeline_step", "severity", "counted_in_blocker_gate"])
      if (!(key in rule)) throw new Error(`dlq_rules.json: rule ${rule.rule_id ?? "?"} lacks "${key}"`);
  return `${HEADER}/** scripts/gui/export_knobs.py → generated/dlq_rules.json, typed: every DLQ rule as the code emits it. */
import type { DlqRule, DlqRulesFile } from "../src/relational";

export type DlqRuleId =
${doc.rules.map((r) => `  | ${tsString(r.rule_id)}`).join("\n")};

export const dlqRules: DlqRulesFile = ${JSON.stringify(doc, null, 2)};

/** rule_id → rule; unknown ids (a newer pipeline) are simply absent. */
export const dlqRuleById: ReadonlyMap<string, DlqRule> = new Map(dlqRules.rules.map((rule) => [rule.rule_id, rule]));
`;
}

function goldenFiles(outDir) {
  const dir = join(outDir, "golden");
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith(".json"))
    .sort();
}

/**
 * Generates every output in memory. `inputsDir` holds the exporters' JSON and golden/ (the
 * Python-owned inputs, which live beside the outputs).
 */
export function generate({ repo, inputsDir }) {
  const tables = loadTables(repo);
  const views = loadViews(repo);
  const catalogueText = readFileSync(join(repo, CATALOGUE), "utf8");
  const catalogue = YAML.parse(catalogueText);
  const knobsText = readFileSync(join(inputsDir, "knobs.json"), "utf8");
  const knobs = JSON.parse(knobsText);
  const relationshipsText = readFileSync(join(inputsDir, "relationships.json"), "utf8");
  const dlqRulesText = readFileSync(join(inputsDir, "dlq_rules.json"), "utf8");

  const inputs = {};
  for (const t of tables) inputs[t.source] = sha256(readFileSync(join(repo, t.source), "utf8"));
  inputs[`${EVAL_SCHEMAS}/views.sql`] = sha256(readFileSync(join(repo, EVAL_SCHEMAS, "views.sql"), "utf8"));
  inputs[CATALOGUE] = sha256(catalogueText);
  inputs["gui/packages/contracts/generated/knobs.json"] = sha256(knobsText);
  inputs["gui/packages/contracts/generated/relationships.json"] = sha256(relationshipsText);
  inputs["gui/packages/contracts/generated/dlq_rules.json"] = sha256(dlqRulesText);
  for (const file of goldenFiles(inputsDir)) {
    const text = readFileSync(join(inputsDir, "golden", file), "utf8");
    const doc = JSON.parse(text);
    if (doc.generated_by !== "scripts/gui/export_golden_fixtures.py")
      throw new Error(`golden/${file}: not written by scripts/gui/export_golden_fixtures.py`);
    inputs[`gui/packages/contracts/generated/golden/${file}`] = sha256(text);
  }

  const files = new Map();
  files.set("schemas.ts", renderSchemas(tables, views, catalogue));
  files.set("catalogue.ts", renderCatalogue(catalogue));
  files.set("knobs.ts", renderKnobs(knobs));
  files.set("relationships.ts", renderRelationships(JSON.parse(relationshipsText)));
  files.set("dlqRules.ts", renderDlqRules(JSON.parse(dlqRulesText)));
  files.set(
    "manifest.json",
    JSON.stringify(
      {
        generator: "gui/packages/contracts/gen.mjs",
        note: "sha256 of every input; contracts:check fails when an input changed without a re-sync.",
        inputs,
        outputs: ["schemas.ts", "catalogue.ts", "knobs.ts", "relationships.ts", "dlqRules.ts"],
      },
      null,
      2,
    ) + "\n",
  );
  return files;
}

/** Compares freshly generated files with `outDir`; returns the drifted relative paths. */
export function diffGenerated(files, outDir) {
  const drift = [];
  for (const [name, content] of files) {
    const path = join(outDir, name);
    const current = existsSync(path) ? readFileSync(path, "utf8") : null;
    if (current !== content) drift.push(name);
  }
  return drift;
}

function parseArgs(argv) {
  const opts = { check: false, repo: resolve(HERE, "../../.."), out: join(HERE, "generated") };
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === "--check") opts.check = true;
    else if (arg === "--repo") opts.repo = resolve(argv[++i]);
    else if (arg === "--out") opts.out = resolve(argv[++i]);
    else throw new Error(`unknown argument ${arg}`);
  }
  return opts;
}

export function main(argv = process.argv.slice(2)) {
  const opts = parseArgs(argv);
  const files = generate({ repo: opts.repo, inputsDir: opts.out });
  if (!opts.check) {
    mkdirSync(opts.out, { recursive: true });
    for (const [name, content] of files) writeFileSync(join(opts.out, name), content);
    console.log(`contracts:sync: wrote ${[...files.keys()].join(", ")} to ${relative(process.cwd(), opts.out) || "."}`);
    return 0;
  }
  // Regenerate into a temporary directory, then diff against the committed files.
  const tmp = mkdtempSync(join(tmpdir(), "contracts-check-"));
  for (const [name, content] of files) writeFileSync(join(tmp, name), content);
  const fresh = new Map([...files.keys()].map((name) => [name, readFileSync(join(tmp, name), "utf8")]));
  const drift = diffGenerated(fresh, opts.out);
  if (drift.length) {
    console.error(
      `contracts:check: ${drift.length} generated file(s) out of date: ${drift.join(", ")}.\n` +
        `A fresh copy is in ${tmp} (diff it against ${opts.out}).\n` +
        "Run `npm run contracts:sync` (and the Python exporters when knobs.json, relationships.json, dlq_rules.json or golden/ changed).",
    );
    return 1;
  }
  rmSync(tmp, { recursive: true, force: true });
  console.log(`contracts:check: ${files.size} generated files match their inputs.`);
  return 0;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    process.exitCode = main();
  } catch (error) {
    console.error(`contracts: ${error instanceof Error ? error.message : String(error)}`);
    process.exitCode = 1;
  }
}
